#!/usr/bin/env python

"""

Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:
           1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

"""

def anwser_1():
    fibo=[1,2]
    while fibo[-1]<4000000:
        fibo.append(fibo[-1]+fibo[-2])
    fibo.pop()
    if fibo[-1]%2==0:
        # A math trick,lol...
        print (sum(fibo)+1)/2
    else:
        print sum([i for i in fibo if i%2==0])

anwser_1()

# Anwser:4613732