#!/usr/bin/env python
#coding:utf-8

"""

Triangular, pentagonal, and hexagonal

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal.

"""
import math

def is_pentagonal(num):
	if (1+math.sqrt(1+24*num))%6==0: return True
	return False

def is_hexagonal(num):
	if (1+math.sqrt(1+8*num))%4==0: return True
	return False

def t(n):
	return n*(n+1)/2

def answer():
	n=285
	while 1:
		n+=1
		tn=t(n)
		if is_hexagonal(tn) and is_pentagonal(tn):
			print tn
			break

import time
tStart=time.time()
answer()
print 'run time=',time.time()-tStart
# 1533776805
# run time= 0.10137295723